/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Employee_info;

import java.awt.FileDialog;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.ResultSetMetaData;
import java.text.ParseException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author U-ser
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        Update_table();
    }
    
    void clearingText() {
        txtID.setText("");
        txtName.setText("");
        jradioMale.setSelected(false);
        jradioFemale.setSelected(false);
        jcbPos.setSelectedIndex(0);
        txtSalary.setText("");
        jDate.setDate(null);
        txtAddress.setText("");
        jcbStatus.setSelectedIndex(0);
        txtName.requestFocus();
        txt_IMG.setText("");
    }
    
    void Update_table() {
        int column;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:33062/users", "root", "");
            String query = "SELECT * FROM employee_info";
            PreparedStatement add = con1.prepareStatement(query);
            ResultSet r = add.executeQuery();
            ResultSetMetaData Rss = r.getMetaData();
            column = Rss.getColumnCount();

            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            table.setRowCount(0);

            while (r.next()) {
                Vector v2 = new Vector();

                for (int i = 1; i <= column; i++) {
                    v2.add(r.getString("ID"));
                    v2.add(r.getString("Name"));
                    v2.add(r.getString("Gender"));
                    v2.add(r.getString("Position"));
                    v2.add(r.getString("Salary"));
                    v2.add(r.getString("Date"));
                    v2.add(r.getString("Address"));
                    v2.add(r.getString("Martial_Status"));
                    v2.add(r.getString("Image"));
                }
                table.addRow(v2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }   
    }      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Connection con1;
    PreparedStatement add;
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSDateChooserBeanInfo1 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelPos = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        labelSalary = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jcbPos = new javax.swing.JComboBox<>();
        jcbStatus = new javax.swing.JComboBox<>();
        jDate = new com.toedter.calendar.JDateChooser();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jradioMale = new javax.swing.JRadioButton();
        jradioFemale = new javax.swing.JRadioButton();
        btnselectImage = new javax.swing.JButton();
        labelImg = new javax.swing.JLabel();
        txt_IMG = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelID.setForeground(new java.awt.Color(0, 0, 0));
        labelID.setText("ID");
        jPanel1.add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 137, -1, -1));

        labelGender.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelGender.setForeground(new java.awt.Color(0, 0, 0));
        labelGender.setText("Gender");
        jPanel1.add(labelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        labelName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 0, 0));
        labelName.setText("Full Name");
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 62, 81, -1));

        labelPos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelPos.setForeground(new java.awt.Color(0, 0, 0));
        labelPos.setText("Position");
        jPanel1.add(labelPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 217, -1, -1));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 281, 34));

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 281, 34));

        txtAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtAddress.setForeground(new java.awt.Color(0, 0, 0));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 240, 281, 34));

        labelSalary.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelSalary.setForeground(new java.awt.Color(0, 0, 0));
        labelSalary.setText("Salary");
        jPanel1.add(labelSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 70, -1, -1));

        labelDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelDate.setForeground(new java.awt.Color(0, 0, 0));
        labelDate.setText("Date Start");
        jPanel1.add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 140, -1, -1));

        labelAddress.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelAddress.setForeground(new java.awt.Color(0, 0, 0));
        labelAddress.setText("Address");
        jPanel1.add(labelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, -1, -1));

        labelStatus.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(0, 0, 0));
        labelStatus.setText("Martial Status");
        jPanel1.add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, -1, -1));

        txtSalary.setBackground(new java.awt.Color(255, 255, 255));
        txtSalary.setForeground(new java.awt.Color(0, 0, 0));
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 281, 34));

        jcbPos.setBackground(new java.awt.Color(255, 255, 255));
        jcbPos.setForeground(new java.awt.Color(0, 0, 0));
        jcbPos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Developer/Engineer", "Systems Analyst", "Network Administrator", "Database Administrator", "IT Project Manager", "Web Developer", "Data Scientist", "Cybersecurity Analyst", "IT Consultant" }));
        jcbPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPosActionPerformed(evt);
            }
        });
        jPanel1.add(jcbPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 281, 37));

        jcbStatus.setBackground(new java.awt.Color(255, 255, 255));
        jcbStatus.setForeground(new java.awt.Color(0, 0, 0));
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Widowed", "Separated", "Unmarried" }));
        jPanel1.add(jcbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 310, 281, 40));

        jDate.setDateFormatString("Select");
        jPanel1.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 281, 34));

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 153, 255));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        btnExit.setBackground(new java.awt.Color(0, 153, 255));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, -1, -1));

        buttonGroup1.add(jradioMale);
        jradioMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jradioMale.setForeground(new java.awt.Color(0, 0, 0));
        jradioMale.setText("male");
        jradioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioMaleActionPerformed(evt);
            }
        });
        jPanel1.add(jradioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, -1));

        buttonGroup1.add(jradioFemale);
        jradioFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jradioFemale.setForeground(new java.awt.Color(0, 0, 0));
        jradioFemale.setText("female");
        jPanel1.add(jradioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        btnselectImage.setBackground(new java.awt.Color(0, 153, 255));
        btnselectImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnselectImage.setForeground(new java.awt.Color(255, 255, 255));
        btnselectImage.setText("Select Image");
        btnselectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectImageActionPerformed(evt);
            }
        });
        jPanel1.add(btnselectImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 270, -1, -1));

        labelImg.setBackground(new java.awt.Color(0, 0, 0));
        labelImg.setForeground(new java.awt.Color(0, 0, 0));
        labelImg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(labelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 60, 200, 200));

        txt_IMG.setBackground(new java.awt.Color(255, 255, 255));
        txt_IMG.setForeground(new java.awt.Color(0, 0, 0));
        txt_IMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IMGActionPerformed(evt);
            }
        });
        jPanel1.add(txt_IMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 310, 201, 31));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gender", "Position", "Salary", "Date Start", "Address", "Martial Status", "ImagePath"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 997, 444));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employee_info/3e563fc5d6ba36ff66a491917ed5ce5f.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(66, 66, 66))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 980));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        txtID.setText(model.getValueAt(selectedIndex, 0).toString());
        txtName.setText(model.getValueAt(selectedIndex, 1).toString());
        String gender = model.getValueAt(selectedIndex, 2).toString();
        if (gender.equals("Male")) {
            jradioMale.setSelected(true);
        } else {
            jradioFemale.setSelected(true);
        }
        jcbPos.setSelectedItem(model.getValueAt(selectedIndex, 3).toString());
        txtSalary.setText(model.getValueAt(selectedIndex, 4).toString());
        Date date;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(selectedIndex, 5));
            jDate.setDate(date);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        txtAddress.setText(model.getValueAt(selectedIndex, 6).toString());
        jcbStatus.setSelectedItem(model.getValueAt(selectedIndex, 7).toString());
        ImageIcon imageIcon = new ImageIcon((String) model.getValueAt(selectedIndex, 8));
        Image image = imageIcon.getImage();
        Image scaledImage = image.getScaledInstance(labelImg.getWidth(), labelImg.getHeight(), Image.SCALE_SMOOTH);
        labelImg.setIcon(new ImageIcon(scaledImage));
    }//GEN-LAST:event_jTable1MouseClicked

    private void txt_IMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IMGActionPerformed

    private void btnselectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectImageActionPerformed
        // TODO add your handling code here:
        FileDialog fileDialog = new FileDialog(Form.this, "Insert Image", FileDialog.LOAD);
        fileDialog.setVisible(true);
        String directory = fileDialog.getDirectory();
        String filename = fileDialog.getFile();
        if (directory != null && filename != null) {
            String imagePath = directory + filename;
            txt_IMG.setText(imagePath);
            ImageIcon imageIcon = new ImageIcon(imagePath);
            Image image = imageIcon.getImage();
            Image scaledImage = image.getScaledInstance(labelImg.getWidth(), labelImg.getHeight(), Image.SCALE_SMOOTH);
            labelImg.setIcon(new ImageIcon(scaledImage));
        }
    }//GEN-LAST:event_btnselectImageActionPerformed

    private void jradioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradioMaleActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        try {
            String id = model.getValueAt(selectedIndex, 0).toString();
            String name = txtName.getText();
            String gender = "";
            if (jradioMale.isSelected()) {
                gender = "Male";
            } else if (jradioFemale.isSelected()) {
                gender = "Female";
            }

            String position = jcbPos.getSelectedItem().toString();
            String salary = txtSalary.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jDate.getDate());
            String address = txtAddress.getText();
            String status = jcbStatus.getSelectedItem().toString();
            String image = txt_IMG.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:33062/users", "root", "");
            PreparedStatement insert = con1.prepareStatement("UPDATE employee_info SET Name=?, Gender=?, Position=?, Salary=?, Date=?, Address=?, Martial_Status=?, Image=? WHERE ID=?");
            insert.setString(1, name);
            insert.setString(2, gender);
            insert.setString(3, position);
            insert.setString(4, salary);
            insert.setString(5, date);
            insert.setString(6, address);
            insert.setString(7, status);
            insert.setString(8, image);
            insert.setString(9, id);

            insert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Record Updated");

            clearingText();
            Update_table();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();

        try {
            int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:33062/users", "root", "");
            PreparedStatement insert = con1.prepareStatement("DELETE FROM employee_info WHERE ID=?");

            insert.setInt(1, id);

            insert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Record Deleted");

            Update_table();
            clearingText();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String name = txtName.getText();
        String gender = "";
        if (jradioMale.isSelected()) {
            gender = "Male";
        } else if (jradioFemale.isSelected()) {
            gender = "Female";
        }
        String position = jcbPos.getSelectedItem().toString();
        String salary = txtSalary.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(jDate.getDate());
        String address = txtAddress.getText();
        String status = jcbStatus.getSelectedItem().toString();
        String image = txt_IMG.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:33062/users", "root", "");
            PreparedStatement insert = con1.prepareStatement("INSERT INTO employee_info (ID, Name, Gender, Position, Salary, Date, Address, Martial_Status, Image) VALUES (?,?,?,?,?,?,?,?,?)");
            insert.setString(1, id);
            insert.setString(2, name);
            insert.setString(3, gender);
            insert.setString(4, position);
            insert.setString(5, salary);
            insert.setString(6, date);
            insert.setString(7, address);
            insert.setString(8, status);
            insert.setString(9, image);

            insert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Record Added");

            clearingText();
            Update_table();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jcbPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnselectImage;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbPos;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JRadioButton jradioFemale;
    private javax.swing.JRadioButton jradioMale;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelImg;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPos;
    private javax.swing.JLabel labelSalary;
    private javax.swing.JLabel labelStatus;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txt_IMG;
    // End of variables declaration//GEN-END:variables
}
